# Generated by Django 4.0.3 on 2022-06-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_room_current_song_room_title_alter_room_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='album_cover',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
