# Generated by Django 4.0.3 on 2022-06-12 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_room_album_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='artist_string',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
